[package]
name = "md2hwp-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
icu_normalizer = { version = "2.3.0", default-features = false, features = ["compiled_data"] }
jsonschema = { version = "0.18.3", default-features = false, features = ["draft202012"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140", features = ["unbounded_depth"] }
